# Generated by Django 4.2.13 on 2024-06-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payfee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='dateCreated',
            new_name='payment_date',
        ),
    ]
